import java.util.Vector;
class main{
public static void main(String args[]){
Vector<String>grocery=new Vector<>();
Vector<String>fruits=new Vector<>();
fruits.add("Mango");
fruits.add("Banana");
fruits.add("Grapes");
fruits.add("Berries");
fruits.add("Apples");
fruits.add("Citrus");
System.out.println("Fruits: "+fruits);//using assAll()
fruits.add("Peaches");
fruits.add("Coconut");
fruits.add("Pears");
fruits.add(2,"Pineapple");
fruits.addAll(fruits);
System.out.println("fruits: "+fruits);
Vector<String>Vegetables=new Vector<>();
Vegetables.add("oinions");
Vegetables.add("tamoto");
Vegetables.add("chilles");
Vegetables.add("garlic");
Vegetables.add("potato");
Vegetables.add("peppers");
Vegetables.add("brocccoli");
Vegetables.add("Carrot");
Vegetables.add("Cabbage");
System.out.println("Vegetables: "+Vegetables);
Vector<String>AnimalProduce=new Vector<>();
AnimalProduce.add("chicken");
AnimalProduce.add("meat");
AnimalProduce.add("fish");
AnimalProduce.add("eggs");
System.out.println("AnimalProduce: "+AnimalProduce);
Vector<String>DairyProducts=new Vector<>();
DairyProducts.add("milk");
DairyProducts.add("eggs");
DairyProducts.add("cheese");
DairyProducts.add("butter");
DairyProducts.add("yogurt");
DairyProducts.add("Ghee");
System.out.println("DairyProducts: "+DairyProducts);
Vector<String>BakeryProducts=new Vector<>();
BakeryProducts.add("Whole_wheat_bread");
BakeryProducts.add("kulchas");
BakeryProducts.add("Bakery_buns");
BakeryProducts.add("Biscuts");
BakeryProducts.add("Cakes");
System.out.println("BakeryProducts: "+BakeryProducts);
Vector<String>Condiments=new Vector<>();
Condiments.add("salt");
Condiments.add("pepper");
Condiments.add("sugar");
System.out.println("Condiments: "+Condiments);
Vector<String>Spices=new Vector<>();
Spices.add("cardamom");
Spices.add("cinnamon");
Spices.add("nutmeg");
Spices.add("Zeera");
Spices.add("Ajwain");
Spices.add("Turmeric");
System.out.println("Spices: "+Spices);
Vector<String>oils_and_sauces=new Vector<>();
oils_and_sauces.add("oil");
oils_and_sauces.add("Mustard_oil");
oils_and_sauces.add("Sunflower_oil");
oils_and_sauces.add("Soy_Sauce");
oils_and_sauces.add("Fish_sauce");
oils_and_sauces.add("vinegar");
oils_and_sauces.add("Tomato_ketchup");
System.out.println("oils_and_sauces: "+oils_and_sauces);
Vector<String>grainsLegumes=new Vector<>();
grainsLegumes.add("Atta");
grainsLegumes.add("Rice");
grainsLegumes.add("Pasta");
System.out.println("grainsLegumes: "+grainsLegumes);
}
}